from fastapi import FastAPI, Request
import uvicorn
import requests
import json

# NEW: Import our local message queue function
from queue_manager import push_to_queue

app = FastAPI(title="Edge-AI Fog Node")

# GitOps Declarative "Source of Truth" Baseline Configuration
GOLDEN_RULES = {
    "nginx-baseline": {
        "expected_replicas": 3,
        "expected_image": "nginx:latest"
    }
}

def analyze_drift_with_llm(target: str, reasons: list) -> str:
    """
    Orchestrates live local inference using Ollama to process infrastructure anomalies.
    Evaluates model capability to generate exact command-line remediation plans.
    """
    print(f"\n[AI-ANALYSIS] Waking up local Edge-AI (Phi-3) to analyze {target} drift...")
    
    prompt = (
        f"System Anomaly Alert: The deployment '{target}' has experienced configuration drift.\n"
        f"Specific issues identified: {', '.join(reasons)}.\n"
        f"Provide a highly accurate, brief technical explanation of the risk and provide "
        f"the exact 'kubectl' shell command required to restore the state to its desired baseline."
    )
    
    try:
        response = requests.post(
            "http://localhost:11434/api/generate", 
            json={
                "model": "phi3:latest",
                "prompt": prompt,
                "stream": False
            },
            timeout=120
        )
        
        if response.status_code == 200:
            result_json = response.json()
            ai_response = result_json.get("response", "Error: No response text generated by model.")
            print(f"\n[AI-REMEDIATION PLAN GENERATED]\n{ai_response}\n")
            return ai_response
        else:
            return f"Model API Error: Received HTTP status code {response.status_code}"
            
    except Exception as e:
        return f"Inference pipeline execution failure: {str(e)}"

@app.post("/api/v1/telemetry")
async def receive_telemetry(request: Request):
    """
    Ingests continuous telemetry logs from edge sensors and evaluates metrics 
    against defined operational baselines.
    """
    payload = await request.json()
    target = payload.get("target")
    metrics = payload.get("metrics")
    
    print(f"\n[FOG NODE] Received incoming telemetry stream for target: {target}...")
    
    rule = GOLDEN_RULES.get(target)
    if rule:
        drift_detected = False
        reasons = []
        
        if metrics.get("actual_replicas") != rule["expected_replicas"]:
            drift_detected = True
            reasons.append(f"Replica mismatch: Expected {rule['expected_replicas']}, Got {metrics.get('actual_replicas')}")
            
        if metrics.get("current_image") != rule["expected_image"]:
            drift_detected = True
            reasons.append(f"Image mismatch: Expected {rule['expected_image']}, Got {metrics.get('current_image')}")
            
        if drift_detected:
            print(f"[ALERT] Active Configuration Drift Detected for {target}!")
            for reason in reasons:
                print(f"  -> {reason}")
            
            ai_remediation = analyze_drift_with_llm(target, reasons)
            
            cloud_payload = {
                "target": target,
                "reasons": reasons,
                "remediation_plan": ai_remediation
            }
            
            # NEW: Asynchronous Decoupled Logic
            try:
                print(f"[FOG NODE] Offloading enriched payload to Local Message Queue...")
                push_to_queue(cloud_payload)
            except Exception as e:
                print(f"[ERROR] Queue insertion failure: {e}")

            return {
                "status": "anomaly_detected", 
                "details": reasons,
                "remediation_plan": ai_remediation
            }
            
    print("[FOG NODE] Infrastructure is healthy. No configuration drift detected.")
    return {"status": "healthy"}

if __name__ == "__main__":
    print("Initializing Edge-AI Fog Node API Gateway on port 8000...")
    uvicorn.run(app, host="0.0.0.0", port=8000)
